"""
Do Not Edit this file. You may and are encouraged to look at it for reference.
Do Not Move on to the next function until its tests report 'ok' or your code
may not work as expected.
"""

import unittest

from test_paddle_001_constructor_and_getters import TestPaddleConstructor
from test_paddle_002_set_position import TestPaddleSetPosition
from test_paddle_003_move import TestPaddleMove

from test_score_board_001_constructor_and_getters import TestScoreBoardConstructor
from test_score_board_002_special_methods import TestScoreBoardMethods

from test_wall_001_constructor_and_getters import TestWallConstructor
